### ISSUE TITLE
Replace leftovers of "Constraint" by "DataConstraint" resp. "MetadataConstraint"

### ISSUE THREAD

**Issue by dosse** [sdmx3mdt/public-consultation#30]
Example: see: MaintainableTypeCodelistType

Also replace "Content constraints" terms in the technical specification document.

**Comment by dosse** [comment]
@sdmx3mdt I have seen also left overs of "Content constraints" in the technical specifications https://metatechltd.sharepoint.com/:w:/s/SDMX30TechnicalSpecifications/EY5Oq7ex2edPr4ZV7oN8QlABcWtiGUuYr6SpJtgv7z-6ig?e=E8AqXT, e.g. "9.3.2 Multiple Content Constraints", "9.3.3 Inheritance of a Content Constraint". Thus the label for documentation should be added too.

**Comment by sdmx3mdt** [comment]
@dosse concerning the XML schemas, J has reviewed this comment and reports that in the case of MaintainableTypeCodelistType, it is correct to include "Constraint" because it is the full list which includes abstract types. The IM has an abstract Constraint and this is what this enumeration represents.

I can see that ConcreteMaintainableTypeCodelistType by contrast lists "DataConstraint" and "MetadataConstraint" as the concrete maintainables.

**Comment by sdmx3mdt** [comment]
@stratosn minor editorial corrections are required to Section 6 where it still refers to 'content constraint':
 "9.3.2 Multiple Content Constraints", "9.3.3 Inheritance of a Content Constraint"

**Comment by sdmx3mdt** [comment]
Section 6 updated to remove outdated references to 'content constraints'.

The XML Schemas have not been altered. In the case of MaintainableTypeCodelistType, it is correct to include "Constraint" because it represents the full list which includes abstract types. The IM has an abstract Constraint and this is what this enumeration represents.
